import type { Dress, User, IncomingLike, OutgoingLike } from "./types"

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Olivia Chen",
    avatar: "",
    location: "San Francisco, CA",
    address: "1847 Fillmore St, Apt 4, San Francisco, CA 94115",
    rating: 4.9,
    dressesListed: 8,
    completedSwaps: 12,
  },
  {
    id: "user-2",
    name: "Sophia Rivera",
    avatar: "",
    location: "Los Angeles, CA",
    address: "620 Sunset Blvd, Unit 12, Los Angeles, CA 90012",
    rating: 4.8,
    dressesListed: 5,
    completedSwaps: 7,
  },
  {
    id: "user-3",
    name: "Emma Thompson",
    avatar: "",
    location: "New York, NY",
    address: "245 W 14th St, Apt 6B, New York, NY 10011",
    rating: 5.0,
    dressesListed: 14,
    completedSwaps: 20,
  },
  {
    id: "user-4",
    name: "Ava Mitchell",
    avatar: "",
    location: "Chicago, IL",
    address: "1130 N Dearborn St, Apt 3, Chicago, IL 60610",
    rating: 4.7,
    dressesListed: 3,
    completedSwaps: 4,
  },
  {
    id: "user-5",
    name: "Isabella Park",
    avatar: "",
    location: "Austin, TX",
    address: "908 E 5th St, Unit 2, Austin, TX 78702",
    rating: 4.9,
    dressesListed: 6,
    completedSwaps: 9,
  },
]

export const currentUser: User = {
  id: "current-user",
  name: "You",
  avatar: "",
  location: "Brooklyn, NY",
  address: "76 Havemeyer St, Apt 2R, Brooklyn, NY 11211",
  rating: 4.8,
  dressesListed: 2,
  completedSwaps: 3,
}

// Dresses owned by OTHER users — these populate the Discover feed
export const mockDresses: Dress[] = [
  {
    id: "dress-1",
    owner: mockUsers[0],
    images: ["/images/dress-1.jpg", "/images/dress-7.jpg", "/images/dress-6.jpg"],
    brand: "Reformation",
    name: "Sage Midi Dress",
    size: "S",
    dressCode: "Garden Party",
    condition: "Excellent",
    color: "Sage Green",
    packageSize: "light",
    notes: "Worn once for a spring wedding. No alterations.",
    createdAt: "2026-02-15",
  },
  {
    id: "dress-2",
    owner: mockUsers[1],
    images: ["/images/dress-2.jpg", "/images/dress-8.jpg"],
    brand: "Realisation Par",
    name: "Blush Silk Slip",
    size: "M",
    dressCode: "Cocktail",
    condition: "Excellent",
    color: "Blush Pink",
    packageSize: "light",
    notes: "Perfect for summer weddings. Fits true to size.",
    createdAt: "2026-02-20",
  },
  {
    id: "dress-3",
    owner: mockUsers[2],
    images: ["/images/dress-3.jpg", "/images/dress-5.jpg"],
    brand: "Marchesa Notte",
    name: "Navy Cocktail Dress",
    size: "S",
    dressCode: "Black Tie",
    condition: "Excellent",
    color: "Navy Blue",
    packageSize: "medium",
    notes: "Stunning beadwork. Dry cleaned and ready to wear.",
    createdAt: "2026-02-22",
  },
  {
    id: "dress-4",
    owner: mockUsers[3],
    images: ["/images/dress-4.jpg", "/images/dress-6.jpg"],
    brand: "BHLDN",
    name: "Champagne Maxi",
    size: "M",
    dressCode: "Semi-Formal",
    condition: "Good",
    color: "Champagne Gold",
    packageSize: "medium",
    notes: "Elegant and flowy. Great for outdoor ceremonies.",
    createdAt: "2026-02-25",
  },
  {
    id: "dress-5",
    owner: mockUsers[4],
    images: ["/images/dress-5.jpg", "/images/dress-3.jpg"],
    brand: "Diane von Furstenberg",
    name: "Burgundy Wrap Dress",
    size: "L",
    dressCode: "Cocktail",
    condition: "Excellent",
    color: "Burgundy",
    packageSize: "light",
    notes: "Classic DVF wrap. Universally flattering.",
    createdAt: "2026-03-01",
  },
  {
    id: "dress-6",
    owner: mockUsers[0],
    images: ["/images/dress-6.jpg", "/images/dress-1.jpg"],
    brand: "Self-Portrait",
    name: "Lavender Floral Midi",
    size: "XS",
    dressCode: "Garden Party",
    condition: "Excellent",
    color: "Lavender",
    packageSize: "light",
    notes: "Gorgeous lace detail. Perfect condition.",
    createdAt: "2026-03-02",
  },
  {
    id: "dress-7",
    owner: mockUsers[2],
    images: ["/images/dress-7.jpg", "/images/dress-4.jpg"],
    brand: "Cult Gaia",
    name: "Emerald Satin Dress",
    size: "S",
    dressCode: "Semi-Formal",
    condition: "Excellent",
    color: "Emerald Green",
    packageSize: "medium",
    notes: "Beautiful draping. Head-turning color.",
    createdAt: "2026-03-03",
  },
  {
    id: "dress-8",
    owner: mockUsers[1],
    images: ["/images/dress-8.jpg", "/images/dress-2.jpg"],
    brand: "Zimmermann",
    name: "Coral A-Line",
    size: "M",
    dressCode: "Garden Party",
    condition: "Good",
    color: "Coral Peach",
    packageSize: "large",
    notes: "Perfect for destination weddings.",
    createdAt: "2026-03-04",
  },
]

// Dresses owned by the CURRENT user — shown in "Your Wardrobe"
export const myDresses: Dress[] = [
  {
    id: "my-dress-1",
    owner: currentUser,
    images: ["/images/dress-2.jpg", "/images/dress-8.jpg"],
    brand: "Saloni",
    name: "Rose Lace Gown",
    size: "M",
    dressCode: "Cocktail",
    condition: "Excellent",
    color: "Blush Pink",
    packageSize: "medium",
    notes: "Worn to one wedding. Professionally cleaned.",
    createdAt: "2026-02-10",
  },
  {
    id: "my-dress-2",
    owner: currentUser,
    images: ["/images/dress-3.jpg", "/images/dress-5.jpg"],
    brand: "Ganni",
    name: "Midnight Velvet Dress",
    size: "S",
    dressCode: "Black Tie",
    condition: "Excellent",
    color: "Navy",
    packageSize: "light",
    notes: "Deep navy velvet. Timeless silhouette.",
    createdAt: "2026-02-12",
  },
]

// Other users who swiped right on MY dresses (incoming interest)
export const mockIncomingLikes: IncomingLike[] = [
  {
    id: "in-1",
    dress: myDresses[0],
    fromUser: mockUsers[1], // Sophia — mutual (you also liked her dress)
    status: "pending",
    createdAt: "2026-03-05",
    messages: [],
  },
  {
    id: "in-2",
    dress: myDresses[1],
    fromUser: mockUsers[2], // Emma — mutual (you also liked her dress)
    status: "pending",
    createdAt: "2026-03-04",
    messages: [],
  },
  {
    id: "in-3",
    dress: myDresses[0],
    fromUser: mockUsers[4], // Isabella — one-sided
    status: "pending",
    createdAt: "2026-03-03",
    messages: [],
  },
]

// Dresses the current user already swiped right on (outgoing interest)
// dress-2 is owned by Sophia and dress-7 by Emma → both create mutual matches
export const mockOutgoingLikes: OutgoingLike[] = [
  {
    id: "out-1",
    dress: mockDresses[1], // Sophia's Blush Silk Slip
    status: "pending",
    createdAt: "2026-03-05",
  },
  {
    id: "out-2",
    dress: mockDresses[6], // Emma's Emerald Satin Dress
    status: "pending",
    createdAt: "2026-03-04",
  },
]
